Anuragjs,c
thiagoyeds/hello-hacktoberfest-2020 pull request #7
Opened 2020-10-30 15:46 UTC by Anurag-ak99

print Hello Hacktoberfest 2020! through Javascript

2020-10-30 16:27 UTC, Anurag-ak99 commented
please check and revert if any error occurs. Thanks

2020-10-30 17:05 UTC, thiagoyeds requested changes
See the change requests and make them, and then I will accept your PR

2020-10-30 17:05 UTC, thiagoyeds commented on C#/hello.cs
> +      Console.WriteLine("Hello Hactoberfest 2020!");
Add "My name is Anurag-ak99!" the phrase, getting "Hello Hactoberfest 2020! My name is Anurag-ak99!"

2020-10-30 17:05 UTC, thiagoyeds commented on C#/hello.cs
> +namespace HelloWorld
Change namespace to Hello

2020-10-30 17:05 UTC, thiagoyeds commented on javascript/anuraghello.js
> +console.log('Hello, Hacktoberfest2020!');
Change log to 'Hello Hactoberfest 2020! My name is Anurag-ak99!'

2020-10-30 17:05 UTC, thiagoyeds commented on javascript/hellohack.js
> +// document.write() is used when you want to print the content to the HTML document.
Delete this file, just keep **hello-Anurag-ak99.js** and **hello-Anurag-ak99.cs**

2020-10-30 17:05 UTC, thiagoyeds commented on javascript/anuraghello.js
> +// There are three ways to print in js
Change filename to **hello-Anurag-ak99.js**

2020-10-30 17:05 UTC, thiagoyeds commented on C#/hello.cs
> +{
Change filename to **hello-Anurag-ak99.cs**

2020-10-31 11:23 UTC, Anurag-ak99 commented on C#/hello.cs
> +      Console.WriteLine("Hello Hactoberfest 2020!");
okay

2020-10-31 12:18 UTC, Anurag-ak99 commented on C#/hello.cs
> +{
I have made all the changes. if everything is okay, then please accept my Pr

2020-10-31 15:14 UTC, thiagoyeds approved these changes
lgtm

2020-10-31 15:15 UTC, merged